# Generated by Django 3.1.7 on 2021-04-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.URLField(blank=True, default='https://place-hold.it/100x60'),
        ),
    ]
