# Generated by Django 3.1.7 on 2021-04-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210428_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.URLField(default='https://place-hold.it/100x60'),
        ),
    ]
