# Generated by Django 3.1.7 on 2021-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20210428_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.URLField(),
        ),
    ]
