# Generated by Django 3.2 on 2021-05-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_resume_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'резюме'},
        ),
    ]
