# Generated by Django 3.1.7 on 2021-04-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20210428_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансии'},
        ),
    ]
