# Generated by Django 3.2 on 2021-05-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_resume_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'резюме', 'verbose_name_plural': 'резюме'},
        ),
    ]
