# Generated by Django 3.2 on 2021-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_resume_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.FileField(blank=True, upload_to='resume_files', verbose_name='Портфолио'),
        ),
    ]
