# Generated by Django 3.2 on 2021-05-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_application_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='writter_phone',
            new_name='written_phone',
        ),
    ]
