# Generated by Django 3.2 on 2021-05-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_resume_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
    ]
