# Generated by Django 3.2 on 2021-05-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_rename_writter_phone_application_written_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_images'),
        ),
    ]
