# Generated by Django 3.2 on 2021-05-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_auto_20210504_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[('Стажер', 'Стажер'), ('Джуниор', 'Джуниор'), ('Мидл', 'Мидл'), ('Синьор', 'Синьор'), ('Лид', 'Лид')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('Не ищу работу', 'Не ищу работу'), ('Рассматриваю предложения', 'Рассматриваю предложения'), ('Ищу работу', 'Ищу работу')], max_length=200, null=True),
        ),
    ]
