# Generated by Django 3.2 on 2021-05-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='media/company_images/default.jpg', upload_to='company_images'),
        ),
    ]
