# Generated by Django 3.2 on 2021-05-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20210504_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True, verbose_name='Портфолио'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(default='backend', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='vacancies.specialty', verbose_name='Специализация'),
        ),
    ]
